server:
  address: 0.0.0.0
  port: 7101
  servlet:
    context-path: /api
    # session共享
    session:
      cookie:
        domain: localhost

spring:
  application:
    name: xunyou
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.132:3306/project_xunyou?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  # redis 配置
  redis:
    database: 5
    host: 192.168.50.132
    port: 6379
  # session 失效时间（分钟）
  session:
    # 两个月
    timeout: 86400
    store-type: redis
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

oss:
  qiniu:
    access-key:
    secret-key:
    bucket:
    url:
    folder-name:
